import React, { useState } from 'react';
import {
  Copy,
  Check,
  Printer,
  RotateCcw,
  Clock,
  Cpu,
  FileText,
} from 'lucide-react';
import { SecurityAnalysis } from '../types';
import { RiskGauge } from './RiskGauge';
import {
  ThreatCategoriesCard,
  SuspiciousPhrasesCard,
  WhySuspiciousCard,
  ActionAdvisoryCards,
} from './ThreatCards';

interface AnalysisReportProps {
  analysis: SecurityAnalysis;
  originalText: string;
  onReset: () => void;
}

export const AnalysisReport: React.FC<AnalysisReportProps> = ({
  analysis,
  originalText,
  onReset,
}) => {
  const [copied, setCopied] = useState(false);

  const formattedDate = new Date(analysis.analyzedAt).toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  const handleCopyReport = async () => {
    const textReport = `==============================
LIFESHIELD AI — SECURITY THREAT REPORT
==============================
Risk Score: ${analysis.riskScore}/100
Risk Level: ${analysis.riskLevel}
Scam Type: ${analysis.scamType || 'N/A'}
Confidence: ${analysis.confidenceScore}%
Model Engine: ${analysis.modelUsed}
Analyzed At: ${new Date(analysis.analyzedAt).toLocaleString()}

SUMMARY:
${analysis.summary}

PRIMARY RECOMMENDED ACTION:
${analysis.recommendedAction || (analysis.recommendedActions && analysis.recommendedActions[0]) || 'N/A'}

KEY REASONS:
${(analysis.reasons || analysis.whySuspicious).map((r) => `- ${r}`).join('\n')}

DETECTED THREAT CATEGORIES:
${analysis.threatCategories.map((t) => `- [${t.severity.toUpperCase()}] ${t.name}: ${t.description}`).join('\n')}

SUSPICIOUS PHRASES DETECTED:
${analysis.suspiciousPhrases.map((p) => `- "${p.phrase}": ${p.reason}`).join('\n')}

WHY THIS IS SUSPICIOUS:
${analysis.whySuspicious.map((w) => `- ${w}`).join('\n')}

RECOMMENDED PROTECTIVE ACTIONS:
${analysis.recommendedActions.map((a) => `[✓] ${a}`).join('\n')}

DO NOT DO THIS:
${analysis.doNotDo.map((d) => `[X] ${d}`).join('\n')}

ORIGINAL MESSAGE ANALYZED:
"""
${originalText}
"""
==============================
Generated by LifeShield AI
`;

    try {
      await navigator.clipboard.writeText(textReport);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      console.warn('Failed to copy to clipboard');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      
      {/* Report Action Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 rounded-2xl bg-slate-900/90 border border-slate-800">
        
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-xl bg-cyan-950/60 border border-cyan-800/50">
            <FileText className="w-5 h-5 text-cyan-400" />
          </div>
          <div>
            <h2 className="text-base font-bold text-white tracking-wide">
              Security Risk Assessment Report
            </h2>
            <div className="flex flex-wrap items-center gap-3 text-xs text-slate-400 mt-0.5">
              <span className="flex items-center space-x-1">
                <Clock className="w-3.5 h-3.5" />
                <span>{formattedDate}</span>
              </span>
              <span>•</span>
              <span className="flex items-center space-x-1 text-cyan-400 font-mono">
                <Cpu className="w-3.5 h-3.5" />
                <span>{analysis.modelUsed}</span>
              </span>
            </div>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto">
          {/* Copy button */}
          <button
            onClick={handleCopyReport}
            className="flex-1 sm:flex-initial inline-flex items-center justify-center space-x-1.5 px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 border border-slate-700 transition-all shadow-sm"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span className="text-emerald-400">Report Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-slate-400" />
                <span>Copy Report</span>
              </>
            )}
          </button>

          {/* Print button */}
          <button
            onClick={handlePrint}
            className="inline-flex items-center justify-center space-x-1.5 px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 border border-slate-700 transition-all shadow-sm"
            title="Print or Export PDF"
          >
            <Printer className="w-4 h-4 text-slate-400" />
            <span className="hidden md:inline">Print</span>
          </button>

          {/* Reset button */}
          <button
            onClick={onReset}
            className="flex-1 sm:flex-initial inline-flex items-center justify-center space-x-1.5 px-4 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-xs font-bold text-slate-950 transition-all shadow-[0_0_15px_rgba(6,182,212,0.3)]"
          >
            <RotateCcw className="w-4 h-4" />
            <span>Analyze New Message</span>
          </button>
        </div>

      </div>

      {/* Main Score Gauge */}
      <RiskGauge
        score={analysis.riskScore}
        level={analysis.riskLevel}
        confidence={analysis.confidenceScore}
      />

      {/* Executive Summary Callout */}
      <div className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800/90 space-y-2">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <span className="text-[11px] font-bold tracking-wider text-cyan-400 uppercase">
            Executive Threat Summary
          </span>
          {analysis.scamType && (
            <span className="px-2.5 py-0.5 rounded-full bg-cyan-950/80 border border-cyan-800 text-[11px] font-bold text-cyan-300">
              Taxonomy: {analysis.scamType}
            </span>
          )}
        </div>
        <p className="text-sm sm:text-base text-slate-200 font-medium leading-relaxed">
          {analysis.summary}
        </p>
      </div>

      {/* Action Advisory: Green Recommended vs Red Do Not Do */}
      <ActionAdvisoryCards
        recommendedActions={analysis.recommendedActions}
        doNotDo={analysis.doNotDo}
      />

      {/* Detected Threats */}
      <ThreatCategoriesCard categories={analysis.threatCategories} />

      {/* Suspicious Phrases Extracted */}
      <SuspiciousPhrasesCard phrases={analysis.suspiciousPhrases} />

      {/* Why It Is Suspicious (Explanation) */}
      <WhySuspiciousCard points={analysis.whySuspicious} />

      {/* Original Analyzed Message Context */}
      <div className="rounded-2xl glass-panel p-5 border border-slate-800/80 space-y-2">
        <span className="text-[11px] font-bold tracking-wider text-slate-400 uppercase">
          Original Analyzed Input Payload
        </span>
        <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 font-mono text-xs text-slate-300 whitespace-pre-wrap break-words leading-relaxed max-h-48 overflow-y-auto">
          {originalText}
        </div>
      </div>

    </div>
  );
};
